# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93870fdea53ce32d69ba4f3a4d81e57c78079320d068819aa26374fbe598c106a77c088793f69d5042fb3c3dbefd13e6bfd4ddc878b5ba093117956e490a65e2

test:
  secret_key_base: e4cf6ff86cd01e2104218addfdcc7c6fe2a7fa0a1bf910cb322660ca91a44078ec0a7df7234cae083538a4ba96561ef4e76b80d75730dabe035c7a0cc0883c9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
